[workspace]
authors = ["hyzhou"]
channels = ["conda-forge"]
name = "HUGSIM"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.11.10"
setuptools = "==78.1.0"

[pypi-dependencies]
torch = { version = "==2.4.1", index = "https://download.pytorch.org/whl/cu118" }
torchvision = { version = "==0.19.1", index = "https://download.pytorch.org/whl/cu118"}
torchmetrics = ">=1.7.1, <2"
roma = ">=1.5.2.1, <2"
matplotlib = ">=3.10.1, <4"
tqdm = ">=4.67.1, <5"
opencv-python = ">=4.11.0.86, <5"
scipy = ">=1.15.2, <2"
einops = ">=0.8.1, <0.9"
trimesh = ">=4.6.6, <5"
tensorboard = ">=2.19.0, <3"
gpustat = ">=1.1.1, <2"
scikit-learn = ">=1.6.1, <2"
open3d = ">=0.18.0, <0.19"
timm = ">=1.0.15, <2"
geometry = ">=0.0.23, <0.0.24"
gymnasium = "==1.1.1"
imageio = ">=2.37.0, <3"
jaxtyping = ">=0.3.1, <0.4"
mediapy = ">=1.2.3, <2"
omegaconf = ">=2.3.0, <3"
pillow = ">=11.2.1, <12"
plyfile = ">=1.1, <2"
pyquaternion = ">=0.9.9, <0.10"
pyyaml = ">=6.0.2, <7"
shapely = ">=2.1.0, <3"
tabulate = ">=0.9.0, <0.10"
protobuf = "==3.20.2"
runx = "==0.0.6"
fire = ">=0.7.0, <0.8"
ninja = ">=1.11.1.4, <2"
h5py = ">=3.13.0, <4"
nose = ">=1.3.7, <2"
dominate = ">=2.9.1, <3"
cffi = ">=1.17.1, <2"
piexif = ">=1.1.3, <2"
jupyter = ">=1.1.1, <2"
ipdb = ">=0.13.13, <0.14"
numpy = ">=1.24.3, <2"
fastapi = "==0.115.12"
uvicorn = "==0.34.2"
huggingface-hub = "==0.31.1"
hf_transfer = "==0.1.9"
